# SELECT *
# FROM ANIMAL_OUTS -- ANIMAL_ID, ANIMAL_TYPE, DATETIME, NAME, SEX_UPON_OUTCOME

# SELECT *
# FROM ANIMAL_INS -- ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME, SEX_UPON_INTAKE

-- 동물의 입양일이 잘못 입력 -> 보호 시작일보다 입양일이 더 빠른 동물의 아이디와 이름을 조회
SELECT i.ANIMAL_ID, i.name
FROM ANIMAL_OUTS o
INNER JOIN ANIMAL_INS i
ON o.ANIMAL_ID = i.ANIMAL_ID
WHERE i.DATETIME > o.DATETIME
ORDER BY i.DATETIME;

