# SELECT *
# FROM ICECREAM_INFO; # FLAVOR, INGREDITENT_TYPE

# SELECT *
# FROM FIRST_HALF; # SHIPMENT_ID, FLAVOR, TOTAL_ORDER

# 아이스크림 성분 타임과 성분 타입에 대한 총주문량 
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) as TOTAL_ORDER
FROM ICECREAM_INFO AS i
INNER JOIN FIRST_HALF AS h
ON i.FLAVOR = h.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER